export default {
  itemId:0,
  index: [
    {
      id: '0',
      name: '草围',
      leftUrl: 'http://localhost:8000/caowei/caowei-now-index/{z}/{x}/{y}.png',
      leftSize: [3307, 4677],
      leftZoom: 2,
      rightUrl: 'http://localhost:8000/caowei/caowei-future-index/{z}/{x}/{y}.png',
      rightSize: [3307, 4677],
      rightZoom: 2,
      sync: false,
    },
    {
      id: '1',
      name: '臣田',
      leftUrl: 'http://localhost:8000/chentian/chentian-now-index/{z}/{x}/{y}.png',
      leftSize: [3307, 4677],
      leftZoom: 2,
      rightUrl: 'http://localhost:8000/chentian/chentian-future-index/{z}/{x}/{y}.png',
      rightSize: [3307, 4677],
      rightZoom: 2,
      sync: true,
    },
    {
      id: '2',
      name: '大铲湾',
      leftUrl: 'http://localhost:8000/dachanwan/dachanwan-now-index/{z}/{x}/{y}.png',
      leftSize: [3307, 4677],
      leftZoom: 2,
      rightUrl: 'http://localhost:8000/dachanwan/dachanwan-future-index/{z}/{x}/{y}.png',
      rightSize: [3307, 4677],
      rightZoom: 2,
      sync: true,
    },
    {
      id: '3',
      name: '凤凰岗',
      leftUrl: 'http://localhost:8000/fenghuanggang/fenghuanggang-now-index/{z}/{x}/{y}.png',
      leftSize: [3307, 4677],
      leftZoom: 2,
      rightUrl: 'http://localhost:8000/fenghuanggang/fenghuanggang-future-index/{z}/{x}/{y}.png',
      rightSize: [3307, 4677],
      rightZoom: 2,
      sync: false,
    },
    {
      id: '4',
      name: '富华',
      leftUrl: 'http://localhost:8000/fuhua/fuhua-now-index/{z}/{x}/{y}.png',
      leftSize: [3307, 4677],
      leftZoom: 2,
      rightUrl: 'http://localhost:8000/fuhua/fuhua-future-index/{z}/{x}/{y}.png',
      rightSize: [3307, 4677],
      rightZoom: 2,
      sync: true,
    },
    {
      id: '5',
      name: '福中福',
      leftUrl: 'http://localhost:8000/fuzhongfu/fuzhongfu-now-index/{z}/{x}/{y}.png',
      leftSize: [4677, 3307],
      leftZoom: 2,
      rightUrl: 'http://localhost:8000/fuzhongfu/fuzhongfu-future-index/{z}/{x}/{y}.png',
      rightSize: [4677, 3307],
      rightZoom: 2,
      sync: true,
    },
    {
      id: '6',
      name: '共乐',
      leftUrl: 'http://localhost:8000/gongle/gongle-now-index/{z}/{x}/{y}.png',
      leftSize: [3307, 4677],
      leftZoom: 2,
      rightUrl: 'http://localhost:8000/gongle/gongle-future-index/{z}/{x}/{y}.png',
      rightSize: [3307, 4677],
      rightZoom: 2,
      sync: false,
    },
    {
      id: '7',
      name: '固戍',
      leftUrl: 'http://localhost:8000/gushu/gushu-now-index/{z}/{x}/{y}.png',
      leftSize: [3307, 4677],
      leftZoom: 2,
      rightUrl: 'http://localhost:8000/gushu/gushu-future-index/{z}/{x}/{y}.png',
      rightSize: [3307, 4677],
      rightZoom: 2,
      sync: true,
    },
    {
      id: '8',
      name: '蚝业',
      leftUrl: 'http://localhost:8000/haoye/haoye-now-index/{z}/{x}/{y}.png',
      leftSize: [4677, 3307],
      leftZoom: 2,
      rightUrl: 'http://localhost:8000/haoye/haoye-future-index/{z}/{x}/{y}.png',
      rightSize: [4677, 3307],
      rightZoom: 2,
      sync: true,
    },
    {
      id: '9',
      name: '河东',
      leftUrl: 'http://localhost:8000/hedong/hedong-now-index/{z}/{x}/{y}.png',
      leftSize: [4677, 3307],
      leftZoom: 2,
      rightUrl: 'http://localhost:8000/hedong/hedong-future-index/{z}/{x}/{y}.png',
      rightSize: [4677, 3307],
      rightZoom: 2,
      sync: true,
    },
    {
      id: '10',
      name: '河西',
      leftUrl: 'http://localhost:8000/hexi/hexi-now-index/{z}/{x}/{y}.png',
      leftSize: [3307, 4677],
      leftZoom: 2,
      rightUrl: 'http://localhost:8000/hexi/hexi-future-index/{z}/{x}/{y}.png',
      rightSize: [3307, 4677],
      rightZoom: 2,
      sync: true,
    },
    {
      id: '11',
      name: '鹤洲',
      leftUrl: 'http://localhost:8000/hezhou/hezhou-now-index/{z}/{x}/{y}.png',
      leftSize: [3307, 4677],
      leftZoom: 2,
      rightUrl: 'http://localhost:8000/hezhou/hezhou-future-index/{z}/{x}/{y}.png',
      rightSize: [3307, 4677],
      rightZoom: 2,
      sync: true,
    },
    {
      id: '12',
      name: '后瑞',
      leftUrl: 'http://localhost:8000/hourui/hourui-now-index/{z}/{x}/{y}.png',
      leftSize: [3307, 4677],
      leftZoom: 2,
      rightUrl: 'http://localhost:8000/hourui/hourui-future-index/{z}/{x}/{y}.png',
      rightSize: [3307, 4677],
      rightZoom: 2,
      sync: true,
    },
    {
      id: '13',
      name: '黄麻布',
      leftUrl: 'http://localhost:8000/huangmabu/huangmabu-now-index/{z}/{x}/{y}.png',
      leftSize: [3307, 4677],
      leftZoom: 2,
      rightUrl: 'http://localhost:8000/huangmabu/huangmabu-future-index/{z}/{x}/{y}.png',
      rightSize: [3307, 4677],
      rightZoom: 2,
      sync: true,
    },
    {
      id: '14',
      name: '黄田',
      leftUrl: 'http://localhost:8000/huangtian/huangtian-now-index/{z}/{x}/{y}.png',
      leftSize: [3307, 4677],
      leftZoom: 2,
      rightUrl: 'http://localhost:8000/huangtian/huangtian-future-index/{z}/{x}/{y}.png',
      rightSize: [3307, 4677],
      rightZoom: 2,
      sync: true,
    },
    {
      id: '15',
      name: '九围',
      leftUrl: 'http://localhost:8000/jiuwei/jiuwei-now-index/{z}/{x}/{y}.png',
      leftSize: [3307, 4677],
      leftZoom: 2,
      rightUrl: 'http://localhost:8000/jiuwei/jiuwei-future-index/{z}/{x}/{y}.png',
      rightSize: [3307, 4677],
      rightZoom: 2,
      sync: true,
    },
    {
      id: '16',
      name: '劳动',
      leftUrl: 'http://localhost:8000/laodong/laodong-now-index/{z}/{x}/{y}.png',
      leftSize: [3307, 4677],
      leftZoom: 2,
      rightUrl: 'http://localhost:8000/laodong/laodong-future-index/{z}/{x}/{y}.png',
      rightSize: [3307, 4677],
      rightZoom: 2,
      sync: true,
    },
    {
      id: '17',
      name: '乐群',
      leftUrl: 'http://localhost:8000/lequn/lequn-now-index/{z}/{x}/{y}.png',
      leftSize: [3307, 4677],
      leftZoom: 2,
      rightUrl: 'http://localhost:8000/lequn/lequn-future-index/{z}/{x}/{y}.png',
      rightSize: [3307, 4677],
      rightZoom: 2,
      sync: true,
    },
    {
      id: '18',
      name: '勒竹角',
      leftUrl: 'http://localhost:8000/lezhujiao/lezhujiao-now-index/{z}/{x}/{y}.png',
      leftSize: [3307, 4677],
      leftZoom: 2,
      rightUrl: 'http://localhost:8000/lezhujiao/lezhujiao-future-index/{z}/{x}/{y}.png',
      rightSize: [3307, 4677],
      rightZoom: 2,
      sync: true,
    },
    {
      id: '19',
      name: '利锦',
      leftUrl: 'http://localhost:8000/lijin/lijin-now-index/{z}/{x}/{y}.png',
      leftSize: [3307, 4677],
      leftZoom: 2,
      rightUrl: 'http://localhost:8000/lijin/lijin-future-index/{z}/{x}/{y}.png',
      rightSize: [3307, 4677],
      rightZoom: 2,
      sync: true,
    },
    {
      id: '20',
      name: '流塘',
      leftUrl: 'http://localhost:8000/liutang/liutang-now-index/{z}/{x}/{y}.png',
      leftSize: [3307, 4677],
      leftZoom: 2,
      rightUrl: 'http://localhost:8000/liutang/liutang-future-index/{z}/{x}/{y}.png',
      rightSize: [3307, 4677],
      rightZoom: 2,
      sync: true,
    },
    {
      id: '21',
      name: '柳竹',
      leftUrl: 'http://localhost:8000/liuzhu/liuzhu-now-index/{z}/{x}/{y}.png',
      leftSize: [3307, 4677],
      leftZoom: 2,
      rightUrl: 'http://localhost:8000/liuzhu/liuzhu-future-index/{z}/{x}/{y}.png',
      rightSize: [3307, 4677],
      rightZoom: 2,
      sync: true,
    },
    {
      id: '22',
      name: '龙腾',
      leftUrl: 'http://localhost:8000/longteng/longteng-now-index/{z}/{x}/{y}.png',
      leftSize: [3307, 4677],
      leftZoom: 2,
      rightUrl: 'http://localhost:8000/longteng/longteng-future-index/{z}/{x}/{y}.png',
      rightSize: [3307, 4677],
      rightZoom: 2,
      sync: true,
    },
    {
      id: '23',
      name: '龙珠',
      leftUrl: 'http://localhost:8000/longzhu/longzhu-now-index/{z}/{x}/{y}.png',
      leftSize: [3307, 4677],
      leftZoom: 2,
      rightUrl: 'http://localhost:8000/longzhu/longzhu-future-index/{z}/{x}/{y}.png',
      rightSize: [3307, 4677],
      rightZoom: 2,
      sync: true,
    },
    {
      id: '24',
      name: '南昌',
      leftUrl: 'http://localhost:8000/nanchang/nanchang-now-index/{z}/{x}/{y}.png',
      leftSize: [3307, 4677],
      leftZoom: 2,
      rightUrl: 'http://localhost:8000/nanchang/nanchang-future-index/{z}/{x}/{y}.png',
      rightSize: [3307, 4677],
      rightZoom: 2,
      sync: true,
    },
    {
      id: '25',
      name: '三围',
      leftUrl: 'http://localhost:8000/sanwei/sanwei-now-index/{z}/{x}/{y}.png',
      leftSize: [3307, 4677],
      leftZoom: 2,
      rightUrl: 'http://localhost:8000/sanwei/sanwei-future-index/{z}/{x}/{y}.png',
      rightSize: [3307, 4677],
      rightZoom: 2,
      sync: true,
    },
    {
      id: '26',
      name: '桃源',
      leftUrl: 'http://localhost:8000/taoyuan/taoyuan-now-index/{z}/{x}/{y}.png',
      leftSize: [3307, 4677],
      leftZoom: 2,
      rightUrl: 'http://localhost:8000/taoyuan/taoyuan-future-index/{z}/{x}/{y}.png',
      rightSize: [3307, 4677],
      rightZoom: 2,
      sync: true,
    },
    {
      id: '27',
      name: '铁岗',
      leftUrl: 'http://localhost:8000/tiegang/tiegang-now-index/{z}/{x}/{y}.png',
      leftSize: [3307, 4677],
      leftZoom: 2,
      rightUrl: 'http://localhost:8000/tiegang/tiegang-future-index/{z}/{x}/{y}.png',
      rightSize: [3307, 4677],
      rightZoom: 2,
      sync: true,
    },
    {
      id: '28',
      name: '西航',
      leftUrl: 'http://localhost:8000/xihang/xihang-now-index/{z}/{x}/{y}.png',
      leftSize: [3307, 4677],
      leftZoom: 2,
      rightUrl: 'http://localhost:8000/xihang/xihang-future-index/{z}/{x}/{y}.png',
      rightSize: [3307, 4677],
      rightZoom: 2,
      sync: true,
    },
    {
      id: '29',
      name: '西乡',
      leftUrl: 'http://localhost:8000/xixiang/xixiang-now-index/{z}/{x}/{y}.png',
      leftSize: [3307, 4677],
      leftZoom: 2,
      rightUrl: 'http://localhost:8000/xixiang/xixiang-future-index/{z}/{x}/{y}.png',
      rightSize: [3307, 4677],
      rightZoom: 2,
      sync: true,
    },
    {
      id: '30',
      name: '盐田',
      leftUrl: 'http://localhost:8000/yantian/yantian-now-index/{z}/{x}/{y}.png',
      leftSize: [3307, 4677],
      leftZoom: 2,
      rightUrl: 'http://localhost:8000/yantian/yantian-future-index/{z}/{x}/{y}.png',
      rightSize: [3307, 4677],
      rightZoom: 2,
      sync: true,
    },
    {
      id: '31',
      name: '永丰',
      leftUrl: 'http://localhost:8000/yongfeng/yongfeng-now-index/{z}/{x}/{y}.png',
      leftSize: [3307, 4677],
      leftZoom: 2,
      rightUrl: 'http://localhost:8000/yongfeng/yongfeng-future-index/{z}/{x}/{y}.png',
      rightSize: [3307, 4677],
      rightZoom: 2,
      sync: true,
    },
    {
      id: '32',
      name: '渔业',
      leftUrl: 'http://localhost:8000/yuye/yuye-now-index/{z}/{x}/{y}.png',
      leftSize: [3307, 4677],
      leftZoom: 2,
      rightUrl: 'http://localhost:8000/yuye/yuye-future-index/{z}/{x}/{y}.png',
      rightSize: [3307, 4677],
      rightZoom: 2,
      sync: true,
    },
    {
      id: '33',
      name: '庄边',
      leftUrl: 'http://localhost:8000/zhuangbian/zhuangbian-now-index/{z}/{x}/{y}.png',
      leftSize: [3307, 4677],
      leftZoom: 2,
      rightUrl: 'http://localhost:8000/zhuangbian/zhuangbian-future-index/{z}/{x}/{y}.png',
      rightSize: [3307, 4677],
      rightZoom: 2,
      sync: true,
    },
    {
      id: '34',
      name: '朱坳',
      leftUrl: 'http://localhost:8000/zhuao/zhuao-now-index/{z}/{x}/{y}.png',
      leftSize: [3307, 4677],
      leftZoom: 2,
      rightUrl: 'http://localhost:8000/zhuao/zhuao-future-index/{z}/{x}/{y}.png',
      rightSize: [3307, 4677],
      rightZoom: 2,
      sync: true,
    },
  ],
};
