export default {
  itemId: 0,
  displayItems: [
    {
      id: 0,
      name: '草围',
      leftUrl: 'http://localhost:8000/caowei/caowei-now-index/{z}/{x}/{y}.png',
      leftSize: [3307, 4677],
      leftZoom: 3,
      rightUrl: 'http://localhost:8000/caowei/caowei-future-index/{z}/{x}/{y}.png',
      rightSize: [3307, 4677],
      rightZoom: 3,
      sync: false,
    },
    {
      id: 1,
      name: '臣田',
      leftUrl: 'http://localhost:8000/chentian/chentian-now-index/{z}/{x}/{y}.png',
      leftSize: [3307, 4677],
      leftZoom: 3,
      rightUrl: 'http://localhost:8000/chentian/chentian-future-index/{z}/{x}/{y}.png',
      rightSize: [3307, 4677],
      rightZoom: 3,
      sync: true,
    },
    {
      id: 2,
      name: '大铲湾',
      leftUrl: 'http://localhost:8000/dachanwan/dachanwan-now-index/{z}/{x}/{y}.png',
      leftSize: [3307, 4677],
      leftZoom: 3,
      rightUrl: 'http://localhost:8000/dachanwan/dachanwan-future-index/{z}/{x}/{y}.png',
      rightSize: [3307, 4677],
      rightZoom: 3,
      sync: true,
    },
    {
      id: 3,
      name: '凤凰岗',
      leftUrl: 'http://localhost:8000/fenghuanggang/fenghuanggang-now-index/{z}/{x}/{y}.png',
      leftSize: [3307, 4677],
      leftZoom: 3,
      rightUrl: 'http://localhost:8000/fenghuanggang/fenghuanggang-future-index/{z}/{x}/{y}.png',
      rightSize: [3307, 4677],
      rightZoom: 3,
      sync: false,
    },
    {
      id: 4,
      name: '富华',
      leftUrl: 'http://localhost:8000/fuhua/fuhua-now-index/{z}/{x}/{y}.png',
      leftSize: [3307, 4677],
      leftZoom: 3,
      rightUrl: 'http://localhost:8000/fuhua/fuhua-future-index/{z}/{x}/{y}.png',
      rightSize: [3307, 4677],
      rightZoom: 3,
      sync: true,
    },
    {
      id: 5,
      name: '福中福',
      leftUrl: 'http://localhost:8000/fuzhongfu/fuzhongfu-now-index/{z}/{x}/{y}.png',
      leftSize: [4677, 3307],
      leftZoom: 3,
      rightUrl: 'http://localhost:8000/fuzhongfu/fuzhongfu-future-index/{z}/{x}/{y}.png',
      rightSize: [4677, 3307],
      rightZoom: 3,
      sync: true,
    },
    {
      id: 6,
      name: '共乐',
      leftUrl: 'http://localhost:8000/gongle/gongle-now-index/{z}/{x}/{y}.png',
      leftSize: [3307, 4677],
      leftZoom: 3,
      rightUrl: 'http://localhost:8000/gongle/gongle-future-index/{z}/{x}/{y}.png',
      rightSize: [3307, 4677],
      rightZoom: 3,
      sync: false,
    },
    {
      id: 7,
      name: '固戍',
      leftUrl: 'http://localhost:8000/gushu/gushu-now-index/{z}/{x}/{y}.png',
      leftSize: [3307, 4677],
      leftZoom: 3,
      rightUrl: 'http://localhost:8000/gushu/gushu-future-index/{z}/{x}/{y}.png',
      rightSize: [3307, 4677],
      rightZoom: 3,
      sync: true,
    },
  ],
};
